#!/usr/bin/env bash

export GOPATH="$HOME/.go"

# PATH=$PATH:$APPENDED_PATH
PATH=$PATH:"$GOPATH/bin"
PATH=$PATH:"$DOTFILES_PATH/bin"

if [ -d "$HOME/.bin" ]; then
	PATH=$PATH:"$HOME/.bin"
fi

if command -v ruby >/dev/null 2>&1; then
	PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
fi
