#!/usr/bin/env bash

export GOPATH="$HOME/.go"

# PATH=$PATH:$APPENDED_PATH
export PATH=$PATH:"$GOPATH/bin"
export PATH=$PATH:"$DOTFILES_PATH/scripts/bin"
export PATH=$PATH:"$HOME/.cargo/bin"

if [ -d "$HOME/.bin" ]; then
	export PATH=$PATH:"$HOME/.bin"
fi

if command -v ruby >/dev/null 2>&1; then
	export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
fi
