#!/usr/bin/env sh

export LC_ALL=C
export LANG=C

print_info() {
    info line_break

    prin "Shell" "bash"
    prin "WM" "bspwm"
    info "Term" term
    info "Font" font
    info "CPU" cpu
    info "GPU" gpu

    info line_break
    info cols
    info line_break

    # info "OS" distro
    # info "Kernel" kernel
    # info "Theme" theme
    # info "Icons" icons
    # info "Resolution" resolution
    # info "CPU Usage" cpu_usage
    # info "Disk" disk
    # info "Battery" battery
    # info "Song" song
    # info "Local IP" localip
    # info "Public IP" publicip
    # info "Users" users
    # info "Birthday" birthday

		wait
}

kernel="off"
kernel_shorthand="on"

distro_shorthand="off"

os_arch="on"

uptime_shorthand="off"

shell_path="off"
shell_version="on"

speed_type="max"
cpu_shorthand="off"
cpu_display="off"
cpu_speed="on"
cpu_cores="logical"
cpu_temp="off"

gpu_brand="on"
refresh_rate="off"

gtk_shorthand="off"
gtk2="on"
gtk3="on"

public_ip_host="http://ident.me"

song_shorthand="off"

birthday_shorthand="off"
birthday_time="on"
birthday_format="+%a %d %b %Y %l:%M %p"

colors=(distro)
bold="on"
underline_enabled="on"
underline_char="-"

color_blocks="on"
block_width=5
block_height=2

progress_char_elapsed="-"
progress_char_total="="

progress_border="on"
progress_length="15"
progress_color_elapsed="distro"
progress_color_total="distro"

memory_display="off"
battery_display="off"
disk_display="on"

backend="kitty"
image_backend="kitty"

image="~/.wallpaper"
thumbnail_dir="$HOME/.cache/thumbnails/neofetch"
crop_mode="normal"
crop_offset="center"
image_size="360px"
gap=1
yoffset=0
xoffset=0
background_color=

ascii="distro"
ascii_distro="auto"
ascii_colors=(distro)
ascii_logo_size="normal"
ascii_bold="on"

scrot="off"
scrot_cmd="scrot -c -d 3"
scrot_dir="$XDG_PICTURES_DIR"
scrot_name="neofetch-$(date +%F-%I-%M-%S-${RANDOM}).png"
image_host="imgur"
imgur_client_id="0e8b44d15e9fc95"

config="on"
config_file="${XDG_CONFIG_HOME:-${HOME}/.config}/neofetch/config"
