#!/bin/sh

# as far as I can tell, this file is only executed when you run startx from the
# TTY

# you probably want to modify xprofile

echo '' > "$HOME/.xstartup_log"
echo "xinitrc" >> "$HOME/.xstartup_log"

# load our xprofile
if [ -f "$HOME/.xprofile" ]; then
	source "$HOME/.xprofile"
fi

# allow a per-device config to override options
if [ -f "$HOME/.env_xinitrc" ]; then
	source "$HOME/.env_xinitrc"
fi

if [ -f "$HOME/.xmodmap" ]; then
	xmodmap "$HOME/.xmodmap"
fi

echo "a" > ~/.xinitrc.log
echo "initrc" > ~/.xstartup_log

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)
export SSH_AUTH_SOCK

# xcape -e 'Control_L=Escape' &

# pulseaudio --start &

# xset s off -dpms &

# redshift &

# urxvtd &

# autocutsel -fork &
# autocutsel -selection PRIMARY -fork &
# autocutsel -selection SECONDARY -fork &

# fire up wm
exec "$DOTFILES_PATH/de/bspwm/wmstart"
