#!/bin/sh

if [[ -z "$XDG_CONFIG_HOME" ]]; then
  export XDG_CONFIG_HOME="$HOME/.config"
fi
if [[ -z "$DOTFILES_PATH" ]]; then
  export DOTFILES_PATH="$XDG_CONFIG_HOME/dotfiles"
fi

echo "xprofile ($DOTFILES_PATH)" >> "$HOME/.xstartup_log"

if [ -f "$DOTFILES_PATH/de/x/loadresources" ]; then
  source "$DOTFILES_PATH/de/x/loadresources"
fi

# keyrepeat settings
xset r rate 250 80 &

# no screen blanking
# xset -dpms &
# xset s noblank &
# xset s off &

if command -v xss-lock >/dev/null 2>&1; then
	if command -v dm-tool >/dev/null 2>&1; then
		# xss-lock -- dm-tool switch-to-greeter &
		:
	fi
fi

if command -v redshift >/dev/null 2>&1; then
	redshift -r -l 39.0997:-94.5786 -t 6500K:3000K &
fi

if [ -f "$HOME/.xmodmap" ]; then
	xmodmap "$HOME/.xmodmap"
fi

if [ -f "$HOME/.env_xprofile" ]; then
	source "$HOME/.env_xprofile"
fi

if command -v xcape >/dev/null 2>&1; then
	xcape -e 'Control_L=Escape' &
fi

if command -v autocutsel >/dev/null 2>&1; then
	autocutsel -fork &
	autocutsel -selection PRIMARY -fork &
fi
