#!/bin/sh

# as far as I can tell, this file is only executed when you run startx from the
# TTY

echo '' > "$HOME/.xstartup_log"
echo "xinitrc" >> "$HOME/.xstartup_log"

# load our xprofile
if [ -f "$HOME/.xprofile" ]; then
	source "$HOME/.xprofile"
fi

# allow a per-device config to override options
if [ -f "$HOME/.env_xinitrc" ]; then
	source "$HOME/.env_xinitrc"
fi

pulseaudio --start &

# fire up wm
exec "$DOTFILES_PATH/de/wmstart"
