#! /bin/sh

# If, for some reason, you have a binary called "bar_init" that happens to run
# all the time, you're going to have some issues with this one.
if [ $(pgrep -cx bar_init) -gt 1 ] ; then
	printf "%s\n" "The bar is already running." >&2
	exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$BAR_FIFO" ] && rm "$BAR_FIFO"
mkfifo "$BAR_FIFO"

bspc config top_padding "$BAR_HEIGHT"
bspc control --subscribe > "$BAR_FIFO" &
"$DOTFILES_PATH/wm/bar/bar_time" &
"$DOTFILES_PATH/wm/bar/bar_battery" &
"$DOTFILES_PATH/wm/bar/bar_pacman" &
"$DOTFILES_PATH/wm/bar/bar_volume" &
"$DOTFILES_PATH/wm/bar/bar_brightness" &

. $HOME/.config/bar/bar_colors

cat "$BAR_FIFO" | $HOME/.config/bar/bar_format | lemonbar -d -u 2 -g x"$BAR_HEIGHT" -f "$BAR_FONT_FAMILY" -F "$COLOR_FOREGROUND" -B "$COLOR_BACKGROUND" &

wait
