#!/usr/bin/env bash

if [[ $UID -ne 0 ]]; then
	echo "Re-running with 'sudo -E'..."
	sudo -E "$0" "$@"
	exit
fi

dfp=$(cd "$(dirname "${BASH_SOURCE[0]}" )/../../" && pwd)
source "${dfp}/env/common/setup_helpers.bash"

cp "$dfp/apps/de/sway/dm-entry" "/usr/share/wayland-sessions/lsway.desktop"

links=(
	# display manager files
	"apps/de/sway/init"                "/usr/bin/sway-lytedev"

	# udev rules
	# TODO: how does this work in nix?
	"apps/udev-rules/gcadapter"        "/etc/udev/rules.d/51-gcadapter.rules"

	# tmpfiles
	# TODO: does this even do anything anymore?
	"apps/tmpfiles/disable-lid-wakeup" "/etc/tmpfiles.d/disable-lid-wakeup.conf"

	# lightdm
	"apps/de/gnome/gdm-tap-to-click"   "/etc/dconf/db/gdm.d/06-tap-to-click"
)

_dotfiles_setup_run_setup "$HOME/.using-lytedev-etcfiles.lock" "${links[@]}"

