#!/bin/sh

echo "xstartup: XINIT" >> "$HOME/.xstartup_log"

if [ -f "$HOME/.xprofile" ]; then
	source "$HOME/.xprofile"
fi

if [ -f "$HOME/.xinitrc.env" ]; then
	source "$HOME/.xinitrc.env"
fi

# start the bar if we want it
if [ "$BAR_ON_XINIT" -eq 1 ]; then
  "$BAR_PATH/start.bash" &
fi

# fire up wm
unclutter &
compton &

exec "$DOTFILES_PATH/env/wm/wmstart"

