#!/bin/sh

if [ -f ~/.fehbg ]; then
  ~/.fehbg &
fi

source "$DOTFILES_PATH/env/x/xloadresources"
source "$DOTFILES_PATH/variables.bash"

# keyrepeat settings
xset r rate 250 80 &

# no screen blanking
xset -dpms &
xset s noblank &
xset s off &

if [ -d "/usr/lib/nvidia" ]; then
	export LD_LIBRARY_PATH=/usr/lib/nvidia
fi

if [ -f "$HOME/.xprofile.env" ]; then
	source "$HOME/.xprofile.env"
fi
