#!/bin/sh

source "$HOME/.dotfiles/variables.bash"

echo '' > "$HOME/.xstartup_log"
echo "xstartup: $DOTFILES_PATH" >> "$HOME/.xstartup_log"

if [ -f "$HOME/.fehbg" ]; then
  "$HOME/.fehbg" &
fi

if [ -f "$DOTFILES_PATH/env/x/xloadresources" ]; then
  source "$DOTFILES_PATH/env/x/xloadresources"
fi

if [ -f "$DOTFILES_PATH/variables.bash" ]; then
  source "$DOTFILES_PATH/variables.bash"
fi

# keyrepeat settings
xset r rate 250 80 &

# no screen blanking
# xset -dpms &
# xset s noblank &
# xset s off &

if [ -d "/usr/lib/nvidia" ]; then
	export LD_LIBRARY_PATH=/usr/lib/nvidia
fi

if [ -f "$HOME/.xprofile.env" ]; then
	source "$HOME/.xprofile.env"
fi

unclutter &
compton &
