" .nvimrc 
" author: daniel@lytedev.io 
" w/ <3
" =========================

" Automatic config file reloading on save
autocmd! bufwritepost .nvimrc source %

" Mapleader
let mapleader = ","

" Better clipboard handling
set clipboard=unnamed

" Normal backspace behavior
set bs=2

" Tab switching
" nnoremap <C-j> :tabprev<CR>
" nnoremap <C-k> :tabnext<CR>

" Indentation
" vnoremap <c-[> <gv
" vnoremap <c-]> >gv

" Syntax highlighting
filetype off
syntax on
set background=dark

" Tab configuration
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab 

" Line numbers, columns, wrapping
set number
set tw=79
set nowrap
set fo-=t
set colorcolumn=80

" Paragraph formatting
vmap Q gq
nmap Q gqap

" History and undo settings
set history=700
set undolevels=700
set nocp " Unnecessary in nvim

" Search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase 

" Disable swap and backup files
set nobackup
set nowritebackup
set noswapfile

" Don't use escape!
inoremap jj <Esc>

" Plugin Management
" =================
set rtp+=~/.nvim/bundle/Vundle.vim
call vundle#begin()

" Self-manage
Plugin 'gmarik/Vundle.vim'

" Plugins
Plugin 'Valloric/YouCompleteMe'
Plugin 'bling/vim-airline'
Plugin 'scrooloose/syntastic'
Plugin 'SirVer/ultisnips'
Plugin 'edsono/vim-matchit'
Plugin 'elzr/vim-json'
Plugin 'honza/vim-snippets'
Plugin 'justinmk/vim-sneak'
Plugin 'kien/ctrlp.vim'
Plugin 'majutsushi/tagbar'
Plugin 'godlygeek/tabular'
Plugin 'plasticboy/vim-markdown'
Plugin 'scrooloose/nerdcommenter'
Plugin 'sjl/gundo.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'tpope/vim-surround'

call vundle#end()
filetype plugin indent on

