#!/bin/sh

# Load .d configs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Use .Xresources
xrdb ~/.Xresources
if [ -a "$HOME/.Xresources.env" ]; then
  xrdb -merge ~/.Xresources.env
fi

# Screen noblanking
xset -dpms &
xset s noblank &
xset s off &

# Keyrepeat rate
xset r rate 300 80 &

# Supposed to rebind caps lock to escape...
# setxkbmap -options caps:escape
xmodmap -e 'clear Lock'
xmodmap -e 'keycode 0x42=Escape'

# Setup google music
if hash GMusicProxy 2>/dev/null; then
  # mpd &
  # GMusicProxy &
  # gmusic-mpd -d ~/.config/mpd/playlists -r $(ls ~/.config/mpd/playlists/*.m3u | head -1) &
  ::
fi

# Wallpaper up ASAP
~/.fehbg &

# Lower priority stuff
redshift & # Makes the screen nice to look at in low light
unclutter & # Hide that mouse cursor

# if [ -z "$IS_PORTABLE"]; then
#   :
# else
compton -c -f --inactive-dim 0.2 -r4 -l-6 -t-6 -o1 -D 5 &
# fi
"$DOTFILES_PATH/wm/bar/bar_watcher" &
sxhkd &
twmnd &
urxvtd &
exec bspwm

