#!/bin/sh

# Load .d configs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Use .Xresources
xrdb ~/.Xresources

# VirtualBox client service
# killall VBoxClient
# VBoxClient-all
# sleep 1

# Place monitors
# xrandr --output VBOX1 --left-of VBOX0 &

# Set wallpaper
if [ -f $HOME/.fehbg ]; then
  eval $(cat $HOME/.fehbg)
fi

xset -dpms &
xset s noblank &
xset s off &

xset r rate 200 50

setxkbmap -options caps:escape

~/.fehbg &

# Window Manager
redshift &
unclutter & # Hide that mouse cursor
# xautolock -time 10 -locker slock &
sxhkd &
"$DOTFILES_PATH/wm/bar/bar_init" &
exec bspwm

