#!/bin/sh

# Load .d configs
if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Use .Xresources
xrdb ~/.Xresources

# VirtualBox client service
killall VBoxClient
VBoxClient-all
sleep 1

# Place monitors
# xrandr --output VBOX1 --left-of VBOX0 &

# Set wallpaper
if [ -f $HOME/.fehbg ]; then
  eval $(cat $HOME/.fehbg)
fi

# Window Manager
unclutter &
sxhkd &
exec bspwm
