"namespace" = { fg = "yellow" }
"module" = { fg = "yellow" }

"type" = { fg = "cyan" }
"type.builtin" = { fg = "cyan" }
"type.enum.variant" = { fg = "white" }
"constructor" = { fg = "white" }
"variable.other.member" = { fg = "white" }

"keyword" = { fg = "blue" }
"keyword.directive" = { fg = "blue" }
"keyword.control" = { fg = "blue" }
"label" = { fg = "blue" }

"special" = { fg = "blue" }
"operator" = { fg = "magenta" }

"punctuation" = { fg = "white" }
"punctuation.delimiter" = { fg = "white" }

"variable" = { fg = "white" }
"variable.parameter" = { fg = "white" }
"variable.builtin" = { fg = "blue" }
"constant" = { fg = "red" }
"constant.builtin" = { fg = "red" }

"function" = { fg = "green" }
"function.builtin" = { fg = "green" }
"function.macro" = { fg = "green" }
"attribute" = { fg = "green" }

"comment" = { fg = "gray" }
"ui.virtual" = "gray"
# "ui.virtual.ruler" = { bg = "#333333" }

"string" = { fg = "yellow" }
"constant.character" = { fg = "yellow" }
"string.regexp" = { fg = "yellow" }
"constant.numeric" = { fg = "blue" }
"constant.character.escape" = { fg = "blue" }

"markup.heading" = "Cyan"
"markup.list" = "red"
"markup.bold" = { fg = "yellow", modifiers = ["bold"] }
"markup.italic" = { fg = "magenta", modifiers = ["italic"] }
"markup.link.url" = { fg = "yellow", modifiers = ["underlined"] }
"markup.link.text" = "blue"
"markup.quote" = "yellow"
"markup.raw" = "green"

"diff.plus" = { fg = "green" }
"diff.delta" = { fg = "blue" }
"diff.minus" = { fg = "red" }

"ui.background" = { fg = "fg", bg = "bg" }

"ui.window" = { bg = "bg" }
"ui.popup" = { bg = "bg", fg = "white" }
"ui.help" = { bg = "bg" }
"ui.menu" = { bg = "bg" }
"ui.menu.selected" = { bg = "blue", fg = "bg" }

"ui.cursor" = { bg = "white", modifiers = ["reversed"] }
"ui.cursor.primary" = { fg = "white", modifiers = ["reversed"] }
"ui.cursor.match" = { fg = "gray", bg = "white", modifiers = ["reversed"] }

"ui.selection" = { bg = "black" }
"ui.selection.primary" = { bg = "black" }

"ui.linenr" = { fg = "gray" }
"ui.linenr.selected" = { fg = "white" }

"ui.statusline" = { fg = "gray", bg = "bg" }
"ui.statusline.inactive" = { fg = "bg", bg = "gray" }

"ui.text" = { fg = "gray", bg = "bg" }
"ui.text.focus" = { fg = "white" }

"warning" = { fg = "yellow" }
"error" = { fg = "red" }
"info" = { fg = "blue" }
"hint" = { fg = "green" }

diagnostic = { underline = { style = "curl" } }
"diagnostic.error" = { underline = { style = "curl", color = "red" } }

"ui.bufferline" = { fg = "gray", bg = "bg" }
"ui.bufferline.active" = { fg = "blue" }
