[[language]]
name = "typescript"
scope = "source.ts"
injection-regex = "ts"
file-types = ["typescript"]
roots = ["deno.json"]
language-server = { command = "denopoo", args = ["lsp"] }
config = { deno = { enable = true, lint = true } }
comment-token = "//"
indent = { tab-width = 2, unit = "  " }
grammar = "javascript"

[[language]]
name = "elixir"
scope = "source.elixir"
injection-regex = "(elixir|ex)"
file-types = ["ex", "exs", "mix.lock"]
shebangs = ["elixir"]
roots = []
comment-token = "#"
auto-format = true
language-server = { command = "elixir-ls" }
config = { elixirLS.dialyzerEnabled = true }
indent = { tab-width = 2, unit = "  " }