#!/usr/bin/env bash

source "$HOME/.bashrc"

# NO_COMPTON=1
BORDER_WIDTH=5 # change in bspwm_config, here for launcher
START_BAR=1
BAR_COMMAND="$DOTFILES_PATH/de/bar/bar.bash"

if [[ -z "$XDG_CONFIG_HOME" ]]; then
	export XDG_CONFIG_HOME="$HOME/.config"
fi
if [[ -z "$DOTFILES_PATH" ]]; then
	export DOTFILES_PATH="$XDG_CONFIG_HOME/dotfiles"
fi

BSPWM_STATE_FILE="$HOME/.bspwm_state"

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

source "$DOTFILES_PATH/de/bspwm/config"

# TODO: switch to alacritty
if command -v urxvtd >/dev/null 2>&1; then
	urxvtd &
fi

if command -v dunst >/dev/null 2>&1; then
	dunst &
fi

if command -v sxhkd >/dev/null 2>&1; then
	# export HIGHLIGHT_COLOR=$(xrdb -query | sed -ne 's/.*font:\s*xft:.*\-\(.*\)$/\1/p' | head -n 1)
	export NICE_HOME
	sxhkd -m -1 &
fi

if [ -f "$DOTFILES_PATH/de/x/loadresources" ]; then
  "$DOTFILES_PATH/de/x/loadresources"
fi

if [ -f "$HOME/.fehbg" ]; then
  "$HOME/.fehbg" &
fi

# launch optional and helpful apps
if command -v unclutter >/dev/null 2>&1; then
  unclutter &
fi

if command -v compton >/dev/null 2>&1; then
	if [[ "$NO_COMPTON" -ne 1 ]]; then
		compton &
	fi
fi

# launch bar
if [[ $START_BAR -eq 1 ]]; then
	${BAR_COMMAND} &
fi

bspc wm -o
