#!/usr/bin/env bash

export GOPATH="$HOME/.go"

# PATH=$PATH:$APPENDED_PATH
export PATH=$PATH:"$GOPATH/bin"
export PATH=$PATH:"$DOTFILES_PATH/scripts/bin"
export PATH=$PATH:"$DOTFILES_PATH/scripts/env_bin"
export PATH=$PATH:"$HOME/.env_bin"
export PATH=$PATH:"$HOME/.cargo/bin"
export PATH=$PATH:"$HOME/.yarn/bin"

if [ -d "$HOME/.local/bin" ]; then
	export PATH=$PATH:"$HOME/.local/bin"
fi

if [ -d "$HOME/.bin" ]; then
	export PATH=$PATH:"$HOME/.bin"
fi

if command -v python >/dev/null 2>&1; then
	export PATH="$(python -m site --user-base)/bin:$PATH"
fi

if command -v ruby >/dev/null 2>&1; then
	export PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"
fi

export NOTES_PATH="$NICE_HOME/doc/notes"

_make_paths() {
	mkdir -p "${NOTES_PATH}"
}
export -f _make_paths
