" .vimrc
" author: daniel@lytedev.io
" w/ <3
" =========================

" Compatibility stuff
filetype off
set nocompatible

" Automatic config file reloading on save
" TODO: Find a more dynamic solution? Editing in the dotfiles repo often causes
" vim to not catch this.
autocmd! bufwritepost .vimrc source %

" Hide splash screen
:set shortmess+=I

" Highlight current line
set cursorline
set cursorcolumn
highlight cursorline cterm=bold ctermbg=black
highlight cursorcolumn cterm=bold ctermbg=black
hi Search ctermfg=white ctermbg=magenta
hi Cursor ctermfg=red

" Code folding
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=1

" Mapleader
let mapleader = ","

" Better clipboard handling
set clipboard=unnamed

" Normal backspace behavior
set bs=2

" Tab switching
" nnoremap <C-j> :tabprev<CR>
" nnoremap <C-k> :tabnext<CR>

" Buffer switching
nnoremap <C-j> :bp<CR>
nnoremap <C-k> :bn<CR>

" Open tag reference in new tab
" nnoremap <C-]> <C-w><C-]><C-w>T

" Indentation
" vnoremap <c-[> <gv
" vnoremap <c-]> >gv

" Tab configuration (python defaults I believe?)
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab

" Tab config for PHP
autocmd FileType php setlocal shiftwidth=2 softtabstop=2 tabstop=2

" Line numbers, columns, wrapping
set number
highlight LineNr ctermbg=darkgrey ctermfg=black
set tw=79
set nowrap
set fo-=t
" set colorcolumn=80

" Paragraph formatting
vmap Q gq
nmap Q gqap

" History and undo settings
set history=700
set undolevels=700
set nocp " Unnecessary in nvim

" Search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase

" Disable swap and backup files
set nobackup
set nowritebackup
set noswapfile

" Don't use escape!
inoremap jj <Esc>

set laststatus=2

" Tags file should be '.tags'
set tags=./.tags;.tags;

" Handy commands
command! RemoveAllTrailingWhitespace :%s/\s\+$//g | let @/ = ""

" Plugin Management
" =================
set rtp+=~/.nvim/bundle/Vundle.vim
call vundle#begin()

" Self-manage
Plugin 'gmarik/Vundle.vim'

" Plugins
" Plugin 'ervandew/supertab'           " Better tab usage
Plugin 'wting/rust.vim'              " Rust support for vim
Plugin 'cespare/vim-toml'            " TOML support for vim
Plugin 'bling/vim-airline'           " Status bar
Plugin 'scrooloose/syntastic'        " File syntax detection
Plugin 'edsono/vim-matchit'          " % matching? included with vim?
Plugin 'SirVer/ultisnips'            " Snippets
Plugin 'honza/vim-snippets'          " Snippets for ultisnips
Plugin 'Valloric/YouCompleteMe'      " Autocompletion
Plugin 'elzr/vim-json'               " Better JSON viewing/editing
Plugin 'justinmk/vim-sneak'          " Two-char super-fast find/goto
Plugin 'kien/ctrlp.vim'              " Arbitrary file opening
Plugin 'majutsushi/tagbar'           " Show file tags
Plugin 'godlygeek/tabular'           " Aligning and table-ing text
Plugin 'plasticboy/vim-markdown'     " Better Markdown viewing/editing
Plugin 'scrooloose/nerdcommenter'    " Better comment handling and editing
Plugin 'sjl/gundo.vim'               " Undo tree viewer
Plugin 'tpope/vim-fugitive'          " Git helper
Plugin 'tpope/vim-surround'          " Handy surrounding selectors
Plugin 'scrooloose/nerdtree'         " File tree viewer
" Plugin 'shawncplus/phpcomplete.vim'  " PHP Completion

" let g:SuperTabDefaultCompletionType = '<C-p>'

" let g:ycm_key_list_select_completion = ['<C-n>', '<Down>', 'Tab']
" let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']

" let g:UltiSnipsExpandTrigger = "<Tab>"
" let g:UltiSnipsJumpForwardTrigger = "<Tab>"
" let g:UltiSnipsJumpBackwardTrigger = "<Tab>"

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = ''
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = ''
let g:airline_left_sep=''
let g:airline_right_sep=''
let g:airline#extensions#tabline#fnamemod = ':t'
" let g:airline#extensions#tabline#formatter = ':t'

let g:ctrlp_working_path_mode = 'a'
let g:ctrlp_cmd = 'CtrlPMRUFiles'
" Make ctrlp open in new tab by default
" let g:ctrlp_prompt_mappings = {
"   \ 'AcceptSelection("e")': ['<C-t>'],
"   \ 'AcceptSelection("t")': ['<CR>', '<2-LeftMouse>'],
"   \ }

autocmd  FileType  php setlocal omnifunc=phpcomplete_extended#YouCompleteMe

call vundle#end()

" Syntax highlighting
filetype plugin indent on
syntax on
set background=dark

