" .vimrc 
" author: daniel@lytedev.io 
" w/ <3
" =========================

" Automatic config file reloading on save 
autocmd! bufwritepost $HOME/.vimrc source %

" Hide splash screen
:set shortmess+=I

" Highlight current line
set cursorline
set cursorcolumn
highlight cursorline cterm=bold ctermbg=black
highlight cursorcolumn cterm=bold ctermbg=black

" Tab names only show filename
set guitablabel=%t\ %M
let g:airline#extensions#tabline#fnamemod = ':t'

" Code folding
set foldmethod=indent
set foldnestmax=10
set nofoldenable
set foldlevel=1

" Mapleader
let mapleader = ","

" Better clipboard handling
set clipboard=unnamed

" Normal backspace behavior
set bs=2

" Tab switching
nnoremap <C-j> :bp<CR>
nnoremap <C-k> :bn<CR>

" Indentation
" vnoremap <c-[> <gv
" vnoremap <c-]> >gv

" Syntax highlighting
filetype off
syntax on
set background=dark

" Tab configuration (python defaults I believe?)
set tabstop=4
set softtabstop=4
set shiftwidth=4
set shiftround
set expandtab 

" Tab config for PHP
autocmd FileType php setlocal shiftwidth=2 softtabstop=2 tabstop=2

" Line numbers, columns, wrapping
set number
highlight LineNr ctermbg=darkgrey ctermfg=black
set tw=79
set nowrap
set fo-=t
" set colorcolumn=80

" Paragraph formatting
vmap Q gq
nmap Q gqap

" History and undo settings
set history=700
set undolevels=700
set nocp " Unnecessary in nvim

" Search case insensitive
set hlsearch
set incsearch
set ignorecase
set smartcase 

" Disable swap and backup files
set nobackup
set nowritebackup
set noswapfile

" Don't use escape!
inoremap jj <Esc>

set laststatus=2

" Plugin Management
" =================
set rtp+=~/.nvim/bundle/Vundle.vim
call vundle#begin()

" Self-manage
Plugin 'gmarik/Vundle.vim'

" Plugins
Plugin 'ervandew/supertab'        " Better tab usage
Plugin 'Valloric/YouCompleteMe'   " Autocompletion
Plugin 'bling/vim-airline'        " Status bar
Plugin 'scrooloose/syntastic'     " File syntax detection
Plugin 'SirVer/ultisnips'         " Snippets
Plugin 'edsono/vim-matchit'       " % matching? included with vim?
Plugin 'elzr/vim-json'            " Better JSON viewing/editing
Plugin 'honza/vim-snippets'       " Snippets for syntastic
Plugin 'justinmk/vim-sneak'       " Two-char super-fast find/goto
Plugin 'kien/ctrlp.vim'           " Arbitrary file opening
Plugin 'majutsushi/tagbar'        " Show file tags
Plugin 'godlygeek/tabular'        " Aligning and table-ing text
Plugin 'plasticboy/vim-markdown'  " Better Markdown viewing/editing
Plugin 'scrooloose/nerdcommenter' " Better comment handling and editing
Plugin 'sjl/gundo.vim'            " Undo tree viewer
Plugin 'tpope/vim-fugitive'       " Git helper
Plugin 'tpope/vim-surround'       " Handy surrounding selectors
Plugin 'scrooloose/nerdtree'      " File tree viewer

let g:SuperTabDefaultCompletionType = '<C-p>'

let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']

let g:UltiSnipsExpandTrigger = "<Tab>"
let g:UltiSnipsJumpForwardTrigger = "<Tab>"
let g:UltiSnipsJumpBackwardTrigger = "<Tab>"

let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#left_sep = ''
let g:airline#extensions#tabline#left_alt_sep = '|'
let g:airline#extensions#tabline#right_sep = ''
let g:airline#extensions#tabline#right_alt_sep = '|'
let g:airline_left_sep=''
let g:airline_right_sep=''

let g:ctrlp_working_path_mode = 'a'

call vundle#end()
filetype plugin indent on

