#!/usr/bin/env sh

bspc config normal_border_color  "#$(get_color 05)"
bspc config focused_border_color "#$(get_color 0B)"
bspc config active_border_color  "#$(get_color 0B)"
bspc config border_width         "$BORDER_WIDTH"
bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true

bspc config window_gap "$WINDOW_GAP"

i=1
for mon in $(bspc query -M); do
    max=$((i + 9))
    bspc monitor "$mon" -d $(seq $i $max)
    i=$((max + 1))
done

