#!/usr/bin/env sh

source "$DOTFILES_PATH/variables.bash"
source "$DOTFILES_PATH/scripts/get_color.sh"
source "$DOTFILES_PATH/scripts/get_x_fonts.sh"

# bspc config normal_border_color   "#$(get_color 05)"
# bspc config focused_border_color  "#$(get_color 0D)"
# bspc config active_border_color   "#$(get_color 0D)"
# bspc config presel_feedback_color "#$(get_color 0D)"

bspc config normal_border_color   "#$(get_color 01)"
bspc config focused_border_color  "#$(get_color 0D)"
bspc config active_border_color   "#$(get_color 0C)"
bspc config presel_feedback_color "#$(get_color 04)"
bspc config border_width          "$BORDER_WIDTH"
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_by_distance     true

bspc config window_gap "$WINDOW_GAP"

MONITOR_COUNT=$(bspc query -M | wc -l | awk '{ printf $1 }')
PER_MONITOR=$((10 / MONITOR_COUNT))
i=1
for mon in $(bspc query -M); do
  echo $mon
  echo $i
  max=$((i + PER_MONITOR - 1))
  echo $max
  bspc monitor "$mon" -d $(seq $i $max)
  i=$((max + 1))
done

