#!/bin/sh

if [ -f ~/.fehbg ]; then
  ~/.fehbg &
fi

source "$DOTFILES_PATH/x/xloadresources"

# keyrepeat settings
xset r rate 300 80 &

# no screen blanking
xset -dpms &
xset s noblank &
xset s off &

# fire up wm
exec bspwm

