#!/bin/sh

if [ -f ~/.fehbg ]; then
  ~/.fehbg &
fi

source "$DOTFILES_PATH/x/xloadresources"
source "$DOTFILES_PATH/variables.bash"

# keyrepeat settings
xset r rate 250 80 &

# no screen blanking
xset -dpms &
xset s noblank &
xset s off &

# start the bar if we want it
if [ "$BAR_ON_XINIT" -eq 1 ]; then
  "$DOTFILES_PATH/wm/extras/bar/start.bash" &
fi

# fire up wm
sxhkd &
exec bspwm

