#!/usr/bin/env bash

userresources=$HOME/.Xresources
usercolors=$HOME/.Xresources.colors
userenv=$HOME/.Xresources.env
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources >/dev/null 2>&1
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap >/dev/null 2>&1
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources" >/dev/null 2>&1
fi

if [ -f "$usercolors" ]; then
    xrdb -merge "$usercolors" >/dev/null 2>&1
fi

if [ -f "$userenv" ]; then
    xrdb -merge "$userenv" >/dev/null 2>&1
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap" >/dev/null 2>&1
fi

if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

