#!/usr/bin/env sh

[ -z "$XDG_CONFIG_HOME" ] && export XDG_CONFIG_HOME="$HOME/.config"
[ -z "$DOTFILES_PATH" ] && export DOTFILES_PATH="$XDG_CONFIG_HOME/dotfiles"

. "$DOTFILES_PATH/bin/prelude"

# killall -9 dunst &> /dev/null
# killall -9 urxvtd
# urxvtd &

# key repeat
export WLC_REPEAT_DELAY=200
export WLC_REPEAT_RATE=60

# caps lock -> escape key mapping
# export XKB_DEFAULT_OPTIONS=caps:escape

# enable wayland support for some applications
export QT_QPA_PLATFORM=wayland-egl
export CLUTTER_BACKEND=wayland
export SDL_VIDEODRIVER=wayland
# export GDK_BACKEND=wayland # DON'T SET THIS ONE
export MOZ_ENABLE_WAYLAND=1

# configuration flag for some of my dotfiles scripts
export IS_WAYLAND=1

sway

# mako &
# has_command libinput-gestures-setup && libinput-gestures-setup start
# has_command kdeconnect-indicator && kdeconnect-indicator &
# has_command gnome-keyring-daemon && eval "$(gnome-keyring-daemon --start --components=pkcs11,secrets,ssh)"
