#!/usr/bin/env sh

NO_COMPTON=1
START_BAR=1
BAR_COMMAND="startbar"

BSPWM_STATE_FILE="$HOME/.bspwm_state"

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

export BORDER_WIDTH=5
. "$DOTFILES_PATH/apps/de/bspwm/config"

[ -f "$DOTFILES_PATH/apps/de/x/loadresources" ] && "$DOTFILES_PATH/apps/de/x/loadresources"
[ -f "$HOME/.fehbg" ] && "$HOME/.fehbg" &
[ "$NO_COMPTON" -ne 1 ] && has_command compton && compton &
[ "$START_BAR" -eq 1 ] && has_command "${BAR_COMMAND}" && "${BAR_COMMAND}" &
has_command urxvtd && urxvtd &
has_command dunst && dunst &
has_command sxhkd && sxhkd -m -1 &
has_command unclutter && unclutter &

bspc wm -o
