#!/usr/bin/env sh

source "$DOTFILES_PATH/variables.bash"
source "$DOTFILES_PATH/scripts/get_color.sh"
source "$DOTFILES_PATH/scripts/get_x_fonts.sh"

# bspc config normal_border_color   "#$(get_color 05)"
# bspc config focused_border_color  "#$(get_color 0D)"
# bspc config active_border_color   "#$(get_color 0D)"
# bspc config presel_feedback_color "#$(get_color 0D)"

bspc config normal_border_color   "#$(get_color 01)"
bspc config focused_border_color  "#$(get_color 0D)"
bspc config active_border_color   "#$(get_color 09)"
bspc config presel_feedback_color "#$(get_color 04)"
bspc config border_width          "$BORDER_WIDTH"
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config window_gap "$WINDOW_GAP"

echo "${BSPWM_MONITORS}"
BSPWM_MONITORS=$(bspc query -M | tac)

MONITOR_COUNT=$(echo "${BSPWM_MONITORS}" | wc -w | awk '{ printf $1 }')
PER_MONITOR=$((10 / MONITOR_COUNT))
i=1
for mon in ${BSPWM_MONITORS}; do
  echo $mon
  echo $i
  max=$((i + PER_MONITOR - 1))
  echo $max
	screens=
	ind="•"
	for j in $(seq $i $max); do
		screens="$screens$ind "
	done
  bspc monitor "$mon" -d $screens
  i=$((max + 1))
done

if [[ -f "$HOME/.bspwm_env" ]]; then
	source "$HOME/.bspwm_env"
fi
