#!/usr/bin/env sh

source "$DOTFILES_PATH/variables.bash"
source "$DOTFILES_PATH/scripts/get_color.sh"
source "$DOTFILES_PATH/scripts/get_x_fonts.sh"

# bspc config normal_border_color   "#$(get_color 05)"
# bspc config focused_border_color  "#$(get_color 0D)"
# bspc config active_border_color   "#$(get_color 0D)"
# bspc config presel_feedback_color "#$(get_color 0D)"

bspc config normal_border_color   "#$(get_color 01)"
bspc config focused_border_color  "#$(get_color 0D)"
bspc config active_border_color   "#$(get_color 09)"
bspc config presel_feedback_color "#$(get_color 04)"
bspc config border_width          "$BORDER_WIDTH"
bspc config split_ratio           0.50
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config window_gap "$WINDOW_GAP"

if [ "$BAR_ON_XINIT" -eq 1 ]; then
	if [ -z "$BAR_MONITOR" -o "$BAR_MONITOR" -eq 0 ]; then
		source "$DOTFILES_PATH/scripts/monitors.sh"
		BAR_MONITOR="$LAST_BSPWM_MONITOR"
	fi

	if [ $BAR_TOP -eq 1 ]; then
		bspc config -m ${BAR_MONITOR} top_padding "$BAR_HEIGHT"
	else
		bspc config -m ${BAR_MONITOR} bottom_padding "$BAR_HEIGHT"
	fi
fi

echo "${BSPWM_MONITORS}"
BSPWM_MONITORS=$(bspc query -M | tac)

MONITOR_COUNT=$(echo "${BSPWM_MONITORS}" | wc -w | awk '{ printf $1 }')
PER_MONITOR=$((10 / MONITOR_COUNT))
i=1

DESKTOPS=(dev web misc env play out main srv daem util)

for mon in ${BSPWM_MONITORS}; do
  echo $mon
  echo $i
  max=$((i + PER_MONITOR - 1))
  echo $max
	screens=
	for j in $(seq $i $max); do
		ind=${DESKTOPS[$((j - 1))]}
		screens="$screens$ind "
	done
  bspc monitor "$mon" -d $screens
  i=$((max + 1))
done

if [[ -f "$HOME/.bspwm_env" ]]; then
	source "$HOME/.bspwm_env"
fi
