#!/usr/bin/env sh

source "$HOME/.dotfiles/variables.bash"

if [ -e "$BSPWM_STATE" ] ; then
	bspc wm -l "$BSPWM_STATE"
	rm "$BSPWM_STATE"
fi

# start the bar if we want it
if [ "$BAR_ON_XINIT" -eq 1 ]; then
  "$BAR_PATH/start.bash" &
fi

source "$DOTFILES_PATH/env/wm/bspwm_config"
source "$DOTFILES_PATH/scripts/get_color.sh"
source "$DOTFILES_PATH/scripts/get_x_fonts.sh"

urxvtd &
sxhkd &

bspc wm -o
